dataops/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.main_page, name="data_main_page"),
    path('import/file/<str:what>', views.Import.as_view(), name="data_import"),
    path('entry/<str:what>', views.Entry.as_view(), name="data_entry"),
    path('import/image', views.image_upload, name="image_upload"),
    path('format/download/<str:what>', views.download_format, name="download_format"),
    path('drop/<str:what>', views.Drop.as_view(), name="data_drop"),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [

    path('', views.main_board, name='main_board'),
    path('model-save/', views.model_save, name='model_save'),
    path('inference/', views.inference_page, name='inference_board'),
    path('inference/upload-image/', views.upload_image, name='upload_image'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

industrial/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.custom_login_view, name="custom_login"),
    path('logout/', views.logout_all, name="custom_logout"),
    path('', views.main, name="main"),
    path('dataops/', include("dataops.urls")),
    path('modeling/', include("modeling.urls")),
    path('prompting/', include("prompting.urls")),   
    path('engine/', include('engine.urls')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dataops/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField


class Recipe(models.Model):

    id = models.IntegerField(primary_key=True)
    bleaching = models.IntegerField(null=False, default=1)
    duration = models.IntegerField(null=False, default=5)
    concentration = models.IntegerField(null=False, default=4000)

    def __str__(self):
        return str(self.id)

class Fabric(models.Model):
    coloring_type = [
        ("halat", "halat"),
        ("Slasher", "Slasher"),
        ("indigo", "indigo"),
        ("Vat dye", "Vat dye")
    ]
    knitting_type = [
        ("2/1 Z", "2/1 Z"),
        ("3/1 Z", "3/1 Z"),
        ("3/1 RHT", "3/1 RHT"),
        ("4/1 SATEN 3 ATLA", "4/1 SATEN 3 ATLA"),
        ("3/1 KIRIK DİMİ", "3/1 KIRIK DİMİ"),
    ]
    id = models.IntegerField(primary_key=True)
    coloring_type = models.CharField(null=False, choices=coloring_type, max_length=180)
    fabric_elasticity = models.IntegerField(null=True)
    yarn_number = models.FloatField(null=True)
    frequency = models.FloatField(null=True)
    knitting = models.CharField(null=True, choices=knitting_type, max_length=180)
    onzyd = models.FloatField(null=True)

    def __str__(self):
        return str(self.id)


class Input(models.Model):

    type = models.ForeignKey(Fabric, null=True, on_delete=models.CASCADE)

    gramaj_raw = models.IntegerField(null=True, blank=True)
    gramaj_hypo = models.IntegerField(null=True, blank=True)

    tearing_strength_weft_raw = models.IntegerField(null=True, blank=True)
    tearing_strength_weft_hypo = models.IntegerField(null=True, blank=True)

    tearing_strength_warp_raw = models.IntegerField(null=True, blank=True)
    tearing_strength_warp_hypo = models.IntegerField(null=True, blank=True)

    breaking_strength_weft_raw = models.IntegerField(null=True, blank=True)
    breaking_strength_weft_hypo = models.IntegerField(null=True, blank=True)

    breaking_strength_warp_raw = models.IntegerField(null=True, blank=True)
    breaking_strength_warp_hypo = models.IntegerField(null=True, blank=True)

    elasticity_raw = models.IntegerField(null=True, blank=True)
    elasticity_hypo = models.IntegerField(null=True, blank=True)

    pot_raw = models.IntegerField(null=True, blank=True)
    pot_hypo = models.IntegerField(null=True, blank=True)

    cielab_l_raw = models.FloatField(null=True, blank=True)
    cielab_l_hypo = models.FloatField(null=True, blank=True)
    cielab_a_raw = models.FloatField(null=True, blank=True)
    cielab_a_hypo = models.FloatField(null=True, blank=True)
    cielab_b_raw = models.FloatField(null=True, blank=True)
    cielab_b_hypo = models.FloatField(null=True, blank=True)

    input_image = models.CharField(null=True, blank=True, max_length=180)

    def __str__(self):
        return str(self.type)

class Experiment(models.Model):

    id = models.CharField(primary_key=True)

    input = models.ForeignKey(Input, null=True, on_delete=models.CASCADE)    
    recipe = models.ForeignKey(Recipe, null=True, on_delete=models.CASCADE) 
    replication = models.IntegerField(null=True, blank=True, default=1)
    gramaj = models.IntegerField(null=True, blank=True)
    tearing_strength_weft = models.IntegerField(null=True, blank=True)
    tearing_strength_warp = models.IntegerField(null=True, blank=True)
    breaking_strength_weft = models.IntegerField(null=True, blank=True)
    breaking_strength_warp = models.IntegerField(null=True, blank=True)
    elasticity = models.IntegerField(null=True, blank=True)
    pot = models.IntegerField(null=True, blank=True)
    cielab_l = models.FloatField(null=True, blank=True)
    cielab_a = models.FloatField(null=True, blank=True)
    cielab_b = models.FloatField(null=True, blank=True)

    output_image = models.CharField(null=True, blank=True, max_length=180)

    def __str__(self):
        return str(self.id)
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.id = str(self.input.type) + "-" + str(self.recipe) + "-" + str(self.replication)
        return super().save(*args, **kwargs)
    
class CustomData(models.Model):
    name = models.CharField(max_length=100)
    form_data = models.JSONField()
    

dataops/views.py
import pandas as pd
import os
import zipfile
import xlwt
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.conf import settings
from django.db.models import Q, Min, Max, Avg
from .models import Recipe, Input, Experiment, Fabric
from .forms import RecipeForm, FabricForm, ExperimentForm, Folder

def main_page(req):

    if req.user.is_authenticated:
        r1 = Recipe.objects.count()
        f1 = Fabric.objects.count()
        e1 = Experiment.objects.count()

        id = Recipe.objects.filter(id__isnull=False).count()
        id_minmax = Recipe.objects.aggregate(min_id=Min("id"), max_id=Max("id"), avg_id=Avg("id"))

        b = Recipe.objects.filter(bleaching__isnull=False).count()
        b_minmax = Recipe.objects.aggregate(min_bleaching=Min("bleaching"), max_bleaching=Max("bleaching"), avg_bl=Avg("bleaching"))

        d = Recipe.objects.filter(duration__isnull=False).count()
        d_minmax = Recipe.objects.aggregate(min_duration=Min("duration"), max_duration=Max("duration"), avg_du=Avg("duration"))

        c = Recipe.objects.filter(concentration__isnull=False).count()
        c_minmax = Recipe.objects.aggregate(min_concentration=Min("concentration"), max_concentration=Max("concentration"), avg_c=Avg("concentration"))

        idf = Fabric.objects.filter(id__isnull=False).count()
        idf_minmax = Fabric.objects.aggregate(min_idf=Min("id"), max_idf=Max("id"), avg_idf=Avg("id"))

        ct = Fabric.objects.filter(coloring_type__isnull=False).count()

        fe = Fabric.objects.filter(fabric_elasticity__isnull=False).count()
        fe_minmax = Fabric.objects.aggregate(min_fe=Min("fabric_elasticity"), max_fe=Max("fabric_elasticity"), avg_fe=Avg("fabric_elasticity"))

        yn = Fabric.objects.filter(yarn_number__isnull=False).count()
        yn_minmax = Fabric.objects.aggregate(min_yn=Min("yarn_number"), max_yn=Max("yarn_number"), avg_yn=Avg("yarn_number"))

        fr = Fabric.objects.filter(frequency__isnull=False).count()
        fr_minmax = Fabric.objects.aggregate(min_fr=Min("frequency"), max_fr=Max("frequency"), avg_fr=Avg("frequency"))

        knit = Fabric.objects.filter(knitting__isnull=False).count()

        onz = Fabric.objects.filter(onzyd__isnull=False).count()
        onz_minmax = Fabric.objects.aggregate(min_onz=Min("onzyd"), max_onz=Max("onzyd"), avg_onz=Avg("onzyd"))

        g = Experiment.objects.filter(gramaj__isnull=False).count()
        g_minmax = Experiment.objects.aggregate(min_gramaj=Min("gramaj"), max_gramaj=Max("gramaj"), avg_g=Avg("gramaj"))

        we = Experiment.objects.filter(tearing_strength_weft__isnull=False).count()
        we_minmax = Experiment.objects.aggregate(min_weft=Min("tearing_strength_weft"), max_weft=Max("tearing_strength_weft"), avg_we=Avg("tearing_strength_weft"))

        wa = Experiment.objects.filter(tearing_strength_warp__isnull=False).count()
        wa_minmax = Experiment.objects.aggregate(min_warp=Min("tearing_strength_warp"), max_warp=Max("tearing_strength_warp"), avg_wa=Avg("tearing_strength_warp"))

        el = Experiment.objects.filter(elasticity__isnull=False).count()
        el_minmax = Experiment.objects.aggregate(min_elasticity=Min("elasticity"), max_elasticity=Max("elasticity"), avg_el=Avg("elasticity"))

        p = Experiment.objects.filter(pot__isnull=False).count()
        p_minmax = Experiment.objects.aggregate(min_pot=Min("pot"), max_pot=Max("pot"), avg_p=Avg("pot"))

        cl = Experiment.objects.filter(cielab_l__isnull=False).count()
        cl_minmax = Experiment.objects.aggregate(min_l=Min("cielab_l"), max_l=Max("cielab_l"), avg_cl=Avg("cielab_l"))

        ca = Experiment.objects.filter(cielab_a__isnull=False).count()
        ca_minmax = Experiment.objects.aggregate(min_a=Min("cielab_a"), max_a=Max("cielab_a"), avg_ca=Avg("cielab_a"))

        cb = Experiment.objects.filter(cielab_b__isnull=False).count()
        cb_minmax = Experiment.objects.aggregate(min_b=Min("cielab_b"), max_b=Max("cielab_b"), avg_cb=Avg("cielab_b"))

        oi = Experiment.objects.filter(output_image__isnull=False).count()
        
        output, raw, hypo, total = 0, 0, 0, 0
        raw_path = os.path.join(settings.MEDIA_ROOT, "data", "raw")
        raw = len([r for r in os.listdir(raw_path) if os.path.isfile(os.path.join(raw_path, r))])
        hypo_path = os.path.join(settings.MEDIA_ROOT, "data", "hypo")
        hypo = len([h for h in os.listdir(hypo_path) if os.path.isfile(os.path.join(hypo_path, h))])
        exp_path = os.path.join(settings.MEDIA_ROOT, "data", "output")
        output = len([e for e in os.listdir(exp_path) if os.path.isfile(os.path.join(exp_path, e))])
        total = output + raw + hypo

        context = {
            "recipe_count": r1,
            "id_count": id,
            "id_minmax": id_minmax,
            "bleaching_count": b,
            "bleaching_minmax": b_minmax,
            "duration_count": d,
            "duration_minmax": d_minmax,
            "concentration_count": c,
            "concentration_minmax": c_minmax,
            "fabric_count": f1,
            "idf_count": idf,
            "idf_minmax": idf_minmax,
            "coloring_count": ct,
            "fabric_e_count": fe,
            "fabric_e_minmax": fe_minmax,
            "yarn_count": yn,
            "yarn_minmax": yn_minmax,
            "freq_count": fr,
            "freq_minmax": fr_minmax,
            "knitting_count": knit,
            "onzyd_count": onz,
            "onzyd_minmax": onz_minmax,
            "experiment_count": e1,
            "gramaj_count": g,
            "gramaj_minmax": g_minmax,
            "weft_count": we,
            "weft_minmax": we_minmax,
            "warp_count": wa,
            "warp_minmax": wa_minmax,
            "elasticity_count": el,
            "elasticity_minmax": el_minmax,
            "pot_count": p,
            "pot_minmax": p_minmax,
            "cielab_l_count": cl,
            "cielab_l_minmax": cl_minmax,
            "cielab_a_count": ca,
            "cielab_a_minmax": ca_minmax,
            "cielab_b_count": cb,
            "cielab_b_minmax": cb_minmax,
            "output_image": oi,
            "total_images": total,
            "raw_images": raw,
            "hypo_images": hypo,
            "output_images": output
        }

        return render(req, "data_main_page.html", context)
    else:
        return HttpResponseRedirect("/accounts/login/?next=/dataops/")

class Import(View):

    template_name = "import_page.html"
    whats = ["recipe", "fabric", "cielab", "gramaj", "weft", "warp", "elasticity", "potluk", "overall"]

    def get(self, req, *args, **kwargs):
        what = kwargs.get("what")
        if what:
            if what in self.whats:
                context = {"what": what}
                return render(req, self.template_name, context)
            else:
                return HttpResponseRedirect("recipe")
        else:
            context = {"message": "ok"}
            return render(req, self.template_name, context)
    
    def post(self, req, *args, **kwargs):
        what = kwargs.get("what")
        if what:
            if what == "recipe":
                message = self.recipe_import(req)
                return HttpResponseRedirect("/dataops")
            elif what == "fabric":
                message = self.fabric_import(req)
                return HttpResponseRedirect("/dataops")
            else:
                message = self.result_import(req, imp=what)
                if message=="success":
                    return HttpResponseRedirect("/dataops")
            context = {"message": message, "what": what} 
            return render(req, self.template_name, context)
    
    def recipe_import(self, req):
        if req.FILES:
            myfile = req.FILES["data_file"]
            content = myfile.content_type
            contents = ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "text/csv"]
            if content not in contents:
                message = "error: provide a csv or xlsx file"
            else:
                try:
                    if content == "text/csv":
                        df = pd.read_csv(myfile)
                    else:
                        df = pd.read_excel(myfile)
                    
                    new_count = 0
                    for d in df.itertuples():
                        id=d.id
                        recep = {
                            "bleaching":d.bleaching,
                            "duration":d.duration, 
                            "concentration":d.concentration
                        }
                        rc, created = Recipe.objects.update_or_create(
                            id=id,
                            defaults=recep)
                        Recipe.save(rc)
                        if created:
                            new_count += 1
                    count = Recipe.objects.count()
                    message = "success: " + str(new_count) + " data imported"
                except Exception as e:
                    message = e   
        else:
            message = "error: provide a csv file"
        return message
    
    def fabric_import(self, req):
        if req.FILES:
            myfile = req.FILES["data_file"]
            content = myfile.content_type
            contents = ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "text/csv"]
            if content not in contents:
                message = "error: provide a csv or xlsx file"
            else:
                try:
                    if content == "text/csv":
                        df = pd.read_csv(myfile)
                    else:
                        df = pd.read_excel(myfile)
                    new_count = 0
                    for d in df.itertuples():

dataops/templates/data_import.html
{% extends "main_template.html" %}
{% load static %}

{% block title %}

Çoklu Giriş

{% endblock %}


{% block content %}

<div class="container-fluid data-import-main">
    <div class="data-form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p><strong>Deney Sonuçlarının Dosyadan Girilmesi:</strong></p>
            <hr>
            <div class="mb-3">
                <div>
                    <label class="form-label" for="id_data_file">Veri Dosyası (.csv, .xlsx)</label>
                </div>
                <input type="file" name="data_file" id="id_data_file" accept=".csv, .xlsx">
            </div>
            <button class="btn btn-success text-center" type="submit">Upload</button>
        </form>
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}  
    </div>
    {% if records %}
    <table class="table table-striped text-successtable-border border-light">
        <thead class="border-light">
            <tr>
                <th scope="col"><strong>Tip</strong></th>
                <th scope="col"><strong>Ham Kumaş Görüntüsü</strong></th>
                <th scope="col"><strong>Reçete</strong></th>
                <th scope="col"><strong>Çıktı Örnekleri</strong></th>
                <th scope="col"><strong>Kopma Mukavemeti (Atkı)</strong></th>
                <th scope="col"><strong>Kopma Mukavemeti (Çözgü)</strong></th>
                <th scope="col"><strong>Yırtılma Mukavemeti (Atkı)</strong></th>
                <th scope="col"><strong>Yırtılma Mukavemeti (Çözgü)</strong></th>
                <th scope="col"><strong>Elastikiyet</strong></th>
                <th scope="col"><strong>Potluk</strong></th>
                <th scope="col"><strong>CIELab L</strong></th>
                <th scope="col"><strong>CIELab a</strong></th>
                <th scope="col"><strong>CIELab b</strong></th>
                <th scope="col"><strong>Stiffness</strong></th>
                <th scope="col"><strong>Alambeta</strong></th>
                <th scope="col"><strong>Kat Geri Dönüşüm</strong></th>
                <th scope="col"><strong>Pilling</strong></th>
                <th scope="col"><strong>Temas Açısı</strong></th>
                <th scope="col"><strong>Hava Geçirgenliği</strong></th>
                <th scope="col"><strong>Aşınma Dayanımı</strong></th>
            </tr>
        </thead>
        <tbody>
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for r in records %}
            <tr>
                <td><input type="text" name="type" class="form-control" value="{{ r.type }}"></td>
                <td><input type="file" name="raw_file{{ forloop.counter }}"></td>
                <td><input type="text" name="recipe" class="form-control" value="{{ r.recipe }}"></td>
                <td><input type="file" name="outputs{{ forloop.counter }}[]"></td>
                <td><input type="text" name="breaking_strength_weft" class="form-control" value="{{ r.breaking_strength_weft }}"></td>
                <td><input type="text" name="breaking_strength_warp" class="form-control" value="{{ r.breaking_strength_warp }}"></td>
                <td><input type="text" name="tearing_strength_weft" class="form-control" value="{{ r.tearing_strength_weft }}"></td>
                <td><input type="text" name="tearing_strength_warp" class="form-control" value="{{ r.tearing_strength_warp }}"></td>
                <td><input type="text" name="elasticity" class="form-control" value="{{ r.elasticity }}"></td>
                <td><input type="text" name="pot" class="form-control" value="{{ r.pot }}"></td>
                <td><input type="text" name="cielab_l" class="form-control" value="{{ r.cielab_l }}"></td>
                <td><input type="text" name="cielab_a" class="form-control" value="{{ r.cielab_a }}"></td>
                <td><input type="text" name="cielab_b" class="form-control" value="{{ r.cielab_b }}"></td>
                <td><input type="text" name="stiffness" class="form-control" value="{{ r.stiffness }}"></td>
                <td><input type="text" name="alambeta" class="form-control" value="{{ r.alambeta }}"></td>
                <td><input type="text" name="recovery" class="form-control" value="{{ r.recovery }}"></td>
                <td><input type="text" name="pilling" class="form-control" value="{{ r.pilling }}"></td>
                <td><input type="text" name="contact_angle" class="form-control" value="{{ r.contact_angle }}"></td>
                <td><input type="text" name="air_permeability" class="form-control" value="{{ r.air_permeability }}"></td>
                <td><input type="text" name="abrasion_resistance" class="form-control" value="{{ r.abrasion_resistance }}"></td>
            </tr>
            {% endfor %}
            <tr>
                <td>
                    <button class="btn btn-success text-center"
                        id="mltiple-data-form-button"
                        type="submit">Gönder
                    </button>
                </td>
            </tr>
        </form>
        </tbody>
    </table>
    {% endif %}
</div>
        
{% endblock %}

dataops/templates/drop_page.html
{% extends "main_template.html" %}
{% load static %}

{% block title %}

Kumaş Verisi Giriş

{% endblock %}

{% block content %}
<div class="container-fluid import-area">
    <div class="data-form" enctype="multipart/form-data" id="grand_form">
        <form method="post">
            {% csrf_token %}
            <p><strong>Veri Silme | {{ what }}</strong></p>
            <hr>
            <p><strong>Aşağıdaki Veri Silinecektir!</strong></p>
            {% if what == "image" %}

            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="1" id="id_raw_image" name="raw_image">
                <label for="id_raw_image" class="form-label">Ham kumaş -{{ raw_number }} adet</label>
            </div>

            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="1" id="id_hypo_image" name="hypo_image">
                <label for="id_hypo_image" class="form-label">Hipo öncesi -{{ hypo_number }} adet </label>
            </div>

            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="1" id="id_out_image" name="out_image">
                <label for="id_out_image" class="form-label">Çıktı -{{ out_number }} adet</label>
            </div>

            <input type="hidden" name="verify" value="{{ what }}" hidden>

            {% else %}

            <p>{{ number }} adet veri silinecektir</p>
            <input type="hidden" name="verify" value="{{ what }}" hidden>
            
            {% endif %}
            <hr>
            <a class="btn btn-success text-center"
                id="ignore-button"
                href="{% url 'data_main_page' %}">Hayır
            </a>
            <button class="btn btn-danger text-center"
                id="drop-button"
                type="submit">Sil
            </button>
        </form>
    </div>
</div>
{% endblock %}

dataops/templates/experiment_form.html
{% extends "main_template.html" %}
{% load static %}

{% block title %}

Sonuç Verisi Girişi

{% endblock %}


{% block content %}
  
<div class="container-fluid entry-page-main">
    <div class="data-form">
        
        <form method="post" enctype="multipart/form-data" id="grand_form">
            {% csrf_token %}
            <p><strong>Veri Girişi | {{ what }}</strong></p>
            <hr>
            <p><strong>Kumaş Tipi:</strong></p>
            <hr>
            <div class="row mb-3">
                <div class="col-4">
                    {{ form.type_number }}
                </div>
                <div class="col-4">
                    <a class="text-warning" href="{% url 'data_entry' 'fabric' %}">Yeni Kumaş Tipi</a>
                </div>
            </div>

            <p><strong>Reçete:</strong></p>
            <hr>
            <div class="row mb-3">               
                <div class="col-4">
                    {{ form.recipe_id }}
                </div>
                <div class="col-4">
                    <a class="text-warning" href="{% url 'data_entry' 'recipe' %}">Yeni Reçete</a>
                </div>
            </div>

            <p><strong>Ölçüm Değerleri:</strong></p>
            <hr>

            <div class="row mb-3">
                <div class="col-3">
                    <label class="form-label" for="id_gramaj">Gramaj</label>
                    {{ form.gramaj }}
                </div>
                <div class="col-3">
                    <label class="form-label" for="id_tearing_strength_weft">Yırtılma Mukavemeti (Atkı)</label>
                    {{ form.tearing_strength_weft }}
                </div>
                <div class="col-3">
                    <label class="form-label" for="id_tearing_strength_warp">Yırtılma Mukavemeti (Çözgü)</label>
                    {{ form.tearing_strength_warp }}
                </div>
                <div class="col-3">
                    <label class="form-label" for="id_elasticity">Elastikiyet</label>
                    {{ form.elasticity }}
                </div>
            </div>

            
            
            <div class="row mb-3">
                <div class="col-4">
                    <label class="form-label" for="id_breaking_strength_weft">Kopma Mukavemeti (Atkı)</label>
                    {{ form.breaking_strength_weft }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_breaking_strength_warp">Kopma Mukavemeti (Çözgü)</label>
                    {{ form.breaking_strength_warp }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_pot">Potluk</label>
                    {{ form.pot }}
                </div>
            </div>

            <div class="row mb-3">
             
                <label class="form-label">CIELab</label>
                <div class="col-4">
                    <label class="form-label" for="id_cielab_l">L</label>
                    {{ form.cielab_l }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_cielab_a">a</label>
                    {{ form.cielab_a }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_cielab_b">b</label>
                    {{ form.cielab_b }}
                </div>
              
            </div>
            <button class="btn btn-success text-center"
                id="data-form-button"
                type="submit">Ekle
            </button>
        </form>
        
    </div>
    
    
</div>
        
{% endblock %}

dataops/templates/fabric_form.html
{% extends "main_template.html" %}
{% load static %}

{% block title %}

Kumaş Verisi Giriş

{% endblock %}

{% block content %}
<div class="container-fluid import-area">
    <div class="data-form" enctype="multipart/form-data" id="grand_form">
        <form method="post">
            {% csrf_token %}
            <p><strong>Veri Girişi | {{ what }}</strong></p>
            <hr>
            <p><strong>Tip Numarası:</strong></p>
            <div class="col-4">
                
                {{ form.fabric_id }}
                
            </div>
            <hr>

            <p><strong>Öznitelikler:</strong></p>
            <hr>

            <div class="row mb-3">
                <div class="col-4">
                    <label class="form-label" for="id_coloring_type">Boyama Tipi</label>
                    {{ form.coloring_type }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_elasticity">Atkı Elastikiyet Ortalaması</label>
                    {{ form.fabric_elasticity }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_yarn_number">İplik Numarası</label>
                    {{ form.yarn_number }}
                </div>
                
            </div>
            <div class="row mb-3">
                <div class="col-4">
                    <label class="form-label" for="id_siklik">Sıklık</label>
                    {{ form.frequency }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_knitting">Örgü</label>
                    {{ form.knitting }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_onzyd">Onz/yd2</label>
                    {{ form.onzyd }}
                </div>
            </div>
            <button class="btn btn-success text-center"
                id="fabric-form-button"
                type="submit">Ekle | Güncelle
            </button>
        </form>
    </div>
</div>
{% endblock %}

dataops/templates/import_page.html
{% extends "main_template.html" %}
{% load static %}

{% block title %}

Çoklu Giriş

{% endblock %}


{% block content %}

<div class="container-fluid data-import-main">
    <div class="data-form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p><strong>Veri Yükleme | {{ what }}</strong></p>
            <hr>
            <div class="mb-3">
                <div>
                    <label class="form-label" for="id_data_file">Veri Dosyası (.csv, .xlsx)</label>
                </div>
                <input type="file" name="data_file" id="id_data_file" accept=".csv, .xlsx">
            </div>
            <button class="btn btn-success text-center" type="submit">Yükle</button>
        </form>
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}  
    </div>
</div>
        
{% endblock %}